version: 2.1

commands:
  param-test:
    parameters:
      flag:
        default: true
        type: boolean
    steps:
      - run:
          name: bash ls command with option "-al"
          command: ls <<# parameters.flag >> -al <</ parameters.flag >>

executors:
  my-executor:
    docker:
      - image: circleci/node:latest

jobs:
  boolean-param-test:
    executor:
      name: my-executor
    steps:
      - run: pwd
      - checkout
      - param-test:
          flag: true

workflows:
  boolean-param-test:
    jobs:
      - boolean-param-test
